### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by joepvtl** [KevinJump/TranslationManager.ContentBlocks#1]
Hi Kevin,

I tried this package with the 8.4.1 version of TranslationManager, but it seems like some interfaces have changed and it doesn't want to boot. Are you open to get a PR for this, or are you willing to do this yourself?

Kind regards,

Joep

**Comment by KevinJump** [comment]
Hi Joep,

if you now what needs fixing then yeah please do push a PR over.

**Comment by joepvtl** [comment]
Hi Kevin,

Hmmm, there are 2 new methods that need to be added to the linkmapper: GetDocType() and GetJsonObject(). For the GetDocType() I know what to do, but for the GetJsonObject() it is unclear to me.

Could you shed some light on what the GetJsonObject is supposed to do?

-Joep

**Comment by joepvtl** [comment]
I created a PR #2 and tested it on a project I am working on and it seems to be good!

Let me know if it needs any changing!

-Joep

**Comment by joepvtl** [comment]
Hey Kevin,

Have you found any time to look into this?

**Comment by KevinJump** [comment]
Hi Sorry, it got lost in the fog of what ever was happening prechristmas. its done now. sorry for the delay.
